# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-18 11:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Conference',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=5, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10, unique=True)),
                ('conference', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Conference')),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('birth_date', models.DateField()),
                ('height', models.DecimalField(decimal_places=2, max_digits=3)),
                ('weight', models.DecimalField(decimal_places=2, max_digits=5)),
                ('college', models.CharField(max_length=60)),
                ('position', models.CharField(max_length=15)),
                ('number', models.IntegerField()),
                ('experience', models.IntegerField()),
                ('draft', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='PlayerStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playoff', models.BooleanField()),
                ('ppg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rpg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('apg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bpg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('spg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tpg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('mpg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ttp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fgp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ftp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ftm', models.IntegerField()),
                ('fgm', models.IntegerField()),
                ('ttm', models.IntegerField()),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Player')),
            ],
            options={
                'ordering': ['season'],
            },
        ),
        migrations.CreateModel(
            name='Season',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=7)),
            ],
        ),
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('fundation_date', models.DateField()),
                ('owner', models.CharField(max_length=60)),
                ('general_manager', models.CharField(max_length=60)),
                ('city', models.CharField(max_length=60)),
                ('arena', models.CharField(max_length=60)),
                ('coach', models.CharField(max_length=60)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Division')),
            ],
        ),
        migrations.CreateModel(
            name='TeamStatistic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('playoff', models.BooleanField()),
                ('ppg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('rpg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('apg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('bpg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('spg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tpg', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ttp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('fgp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ftp', models.DecimalField(decimal_places=2, max_digits=5)),
                ('wins', models.IntegerField()),
                ('loses', models.IntegerField()),
                ('oppPts', models.DecimalField(decimal_places=2, max_digits=5)),
                ('season', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Season')),
                ('team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Team')),
            ],
            options={
                'ordering': ['season'],
            },
        ),
        migrations.AddField(
            model_name='season',
            name='champion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Team'),
        ),
        migrations.AddField(
            model_name='playerstatistic',
            name='season',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Season'),
        ),
        migrations.AddField(
            model_name='player',
            name='team',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.Team'),
        ),
        migrations.AlterUniqueTogether(
            name='teamstatistic',
            unique_together=set([('season', 'team', 'playoff')]),
        ),
        migrations.AlterUniqueTogether(
            name='playerstatistic',
            unique_together=set([('season', 'player', 'playoff')]),
        ),
    ]
