# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-24 04:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='conference',
            name='id_nba',
            field=models.CharField(default='', max_length=80, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='division',
            name='id_nba',
            field=models.CharField(default=' ', max_length=80, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='player',
            name='id_nba',
            field=models.CharField(default=1, max_length=80, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='team',
            name='id_nba',
            field=models.CharField(default=' ', max_length=80, unique=True),
            preserve_default=False,
        ),
    ]
