# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-31 00:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_auto_20171024_0218'),
    ]

    operations = [
        migrations.CreateModel(
            name='Schedule',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scheduled_date', models.DateTimeField()),
                ('home_points', models.IntegerField()),
                ('visitor_points', models.IntegerField()),
                ('home_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='home_team', to='app.Team')),
                ('visitor_team', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visitor_team', to='app.Team')),
            ],
        ),
    ]
