# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-12-05 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_auto_20171112_2142'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='player',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='season',
            name='champion',
        ),
        migrations.RemoveField(
            model_name='team',
            name='awards',
        ),
        migrations.RemoveField(
            model_name='team',
            name='retired_numbers',
        ),
        migrations.AddField(
            model_name='conference',
            name='name_br',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='division',
            name='name_br',
            field=models.CharField(default='', max_length=15),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='conference',
            name='id_nba',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='division',
            name='id_nba',
            field=models.CharField(max_length=80),
        ),
        migrations.AlterField(
            model_name='player',
            name='college',
            field=models.CharField(default='nenhuma', max_length=60, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='draft',
            field=models.CharField(max_length=15),
        ),
        migrations.AlterField(
            model_name='player',
            name='height',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='player',
            name='number',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.AlterField(
            model_name='player',
            name='team',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Team'),
        ),
        migrations.AlterField(
            model_name='player',
            name='weight',
            field=models.CharField(max_length=5),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='fgp',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='ftp',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='playerstatistic',
            name='ttp',
            field=models.DecimalField(decimal_places=3, max_digits=5),
        ),
        migrations.AlterField(
            model_name='team',
            name='division',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='app.Division'),
        ),
        migrations.AlterField(
            model_name='team',
            name='fundation_date',
            field=models.IntegerField(),
        ),
        migrations.DeleteModel(
            name='PlayerAward',
        ),
        migrations.DeleteModel(
            name='RetiredNumber',
        ),
        migrations.DeleteModel(
            name='TeamAward',
        ),
    ]
